import { test, expect } from '@playwright/test';

for (const theme of ['light', 'dark']) {
  test(`Study page and four shared dialogs (${theme})`, async ({ page }, info) => {
    const members = Array.from({ length: 13 }, (_, i) => ({ member_id: i + 1, display_name: `Member ${i + 1}`, joined_at: '2026-10-09', member_status: 'active', contact_email: `member${i + 1}@example.test` }));
    const group = { id: 11, name: 'Discipleship group', status: 'active', curriculum: 'Romans', current_chapter: 'Chapter 5', progress_stage: 'midway', progress_notes: 'A long lesson notice: reading chapter five and preparing for a discussion of verses one through seventeen.', meeting_day: 'Wednesday', meeting_time: '7:00 PM', location: 'Worship Hall', category: 'General', max_capacity: 13, current_member_count: 13, leader_name: 'Test Leader', members };
    const transitions = [{ id: 1, transition_type: 'merge', new_group_id: 11, new_group_name: group.name, effective_date: '2026-10-09', created_at: '2026-10-09', reason: 'Group restructuring', notes: '', source_groups: [{ id: 2, name: 'Source One', leader_name: 'First Leader' }, { id: 3, name: 'Source Two', leader_name: 'Second Leader' }] }];
    const session = { id: 7, session_date: '2026-10-07', topic_title: 'Romans', chapter: 'Chapter 3', progress_stage: 'review', notes: '', recorded_by_name: 'Test Leader', present_count: 13, absent_count: 0, excused_count: 0, attendees: [], absentees: [], excused: [] };
    const mutations: string[] = [], errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(theme => {
      sessionStorage.setItem('dpc_intro_shown', 'true');
      localStorage.setItem('chms_token', 'e30.' + btoa(JSON.stringify({ exp: 4102444800 })) + '.test');
      localStorage.setItem('dpc_theme_mode', theme);
      localStorage.setItem('dpc_help_welcome_v1:1:Pastor', 'seen');
    }, theme);
    await page.route('**/api/**', async route => {
      const path = new URL(route.request().url()).pathname;
      if (route.request().method() !== 'GET') mutations.push(path);
      let json: any = [];
      if (path.endsWith('/auth/setup-status')) json = { hasUsers: true, hasAdmin: true };
      else if (path.endsWith('/auth/me')) json = { user: { id: 1, name: 'Test Pastor', email: 'pastor@example.test', role_name: 'Pastor', ministries: [] } };
      else if (path.endsWith('/groups')) json = [group, { ...group, id: 12, name: 'Second group', progress_notes: '', members: [], current_member_count: 0 }];
      else if (path.endsWith('/groups/transitions')) json = transitions;
      else if (path.endsWith('/groups/11/history')) json = { group, created_transition: transitions[0], merged_into_group: null };
      else if (path.endsWith('/groups/11/attendance')) json = { group, sessions: [session], summary: {}, members: [] };
      else if (path.endsWith('/study-topics')) json = { topics: [], total_count: 0 };
      else if (path.endsWith('/notifications')) json = { items: [], unread_count: 0 };
      else if (path.endsWith('/reports/dashboard')) json = { metrics: {}, ministry_breakdown: [] };
      else if (path.endsWith('/members/birthdays')) json = { celebrants: [], counts: {} };
      else if (path.endsWith('/members/baptism-candidates/qualified')) json = { candidates: [], counts: {} };
      else if (path.endsWith('/settings/general')) json = { settings: {}, list: [] };
      await route.fulfill({ json });
    });
    await page.goto('/');
    await page.locator('aside').getByTitle('Bible Study Groups', { exact: true }).click();
    const card = page.getByRole('article', { name: group.name, exact: true });
    await expect(card).toBeVisible();
    const contrasts = await page.evaluate(() => {
      const parse = (value: string) => value.match(/[\d.]+/g)!.map(Number);
      const over = (c: number[], b: number[]) => c.slice(0, 3).map((v, i) => v * (c[3] ?? 1) + b[i] * (1 - (c[3] ?? 1)));
      const lum = (rgb: number[]) => rgb.map(v => { v /= 255; return v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4; }).reduce((s, v, i) => s + v * [.2126, .7152, .0722][i], 0);
      const host = document.createElement('div'); host.style.background = 'var(--surface-2)'; document.body.append(host);
      const results = ['success', 'warning', 'danger', 'info', 'neutral'].map(variant => {
        const badge = document.createElement('span'); badge.className = `ui-badge ui-badge--${variant}`; host.append(badge);
        const style = getComputedStyle(badge), bg = over(parse(style.backgroundColor), parse(getComputedStyle(host).backgroundColor));
        const a = lum(parse(style.color)), b = lum(bg);
        return { variant, ratio: (Math.max(a, b) + .05) / (Math.min(a, b) + .05) };
      }); host.remove(); return results;
    });
    for (const result of contrasts) expect(result.ratio, `${theme} ${result.variant}`).toBeGreaterThanOrEqual(4.5);
    await info.attach('status-contrast', { body: JSON.stringify(contrasts, null, 2), contentType: 'application/json' });
    await expect(page.getByRole('button', { name: 'Clear filters', exact: true })).toHaveCount(0);
    await page.getByLabel('Filter group meeting day').selectOption('Wednesday');
    await expect(page.getByRole('button', { name: 'Clear filters', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await expect(card.locator('.study-pacing-notice')).toHaveAttribute('title', group.progress_notes);
    const heights = await page.locator('.study-group-card').evaluateAll(cards => cards.map(card => card.getBoundingClientRect().height));
    expect(heights[0]).toBe(heights[1]);
    await page.screenshot({ path: info.outputPath(`groups-${theme}.png`) });
    const roster = card.getByRole('button', { name: 'View Roster (13)', exact: true });
    await roster.click();
    let dialog = page.getByRole('dialog', { name: group.name, exact: true });
    await expect(dialog).toContainText('13 enrolled · Capacity 13');
    await expect(dialog).toContainText('Joined Oct 9, 2026');
    await expect(dialog.getByText('At Capacity', { exact: true })).toBeVisible();
    await expect(dialog.getByRole('progressbar', { name: 'Study curriculum completion' })).toHaveAttribute('aria-valuenow', '4');
    await expect(dialog.getByRole('progressbar', { name: 'Study curriculum completion' })).toHaveAttribute('aria-valuemax', '16');
    await expect(dialog.locator('.study-roster-row')).toHaveCount(5);
    await dialog.getByRole('button', { name: 'View remaining 8 enrolled members' }).click();
    await expect(dialog.locator('.study-roster-row')).toHaveCount(13);
    await dialog.getByRole('button', { name: 'Show fewer members' }).click();
    await expect(dialog.locator('.study-roster-row')).toHaveCount(5);
    await dialog.getByRole('textbox', { name: 'Search enrolled members' }).fill('Member 13');
    await expect(dialog.locator('.study-roster-row')).toHaveCount(1);
    await dialog.getByRole('button', { name: 'Profile of Member 13', exact: true }).click();
    const profile = page.getByRole('dialog', { name: 'Member 13', exact: true });
    await expect(profile).toContainText('member13@example.test');
    await expect(profile).toContainText('Enrolled');
    await expect(profile).toContainText('No phone recorded');
    await page.keyboard.press('Escape');
    await expect(profile).toHaveCount(0);
    await expect(dialog.getByRole('button', { name: 'Profile of Member 13', exact: true })).toBeFocused();
    await dialog.getByRole('textbox', { name: 'Search enrolled members' }).fill('No such member');
    await expect(dialog).toContainText('No members match your search.');
    await dialog.getByRole('textbox', { name: 'Search enrolled members' }).fill('');
    expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden');
    await dialog.getByRole('button', { name: 'More group detail actions' }).click();
    await expect(page.getByRole('menuitem', { name: 'Archive Group' })).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('menu')).toHaveCount(0);
    await expect(dialog).toBeVisible();
    await expect(dialog.getByRole('button', { name: 'More group detail actions' })).toBeFocused();
    await dialog.getByRole('button', { name: 'Update Progress', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Update Study Chapter', exact: true })).toBeVisible();
    await expect(dialog).toHaveCount(0);
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await roster.click();
    await dialog.getByRole('button', { name: 'Timeline', exact: true }).click();
    const history = page.getByRole('dialog', { name: 'Group Transition History', exact: true });
    await expect(history).toContainText('Leadership Record');
    await expect(history).toContainText('Oct 9, 2026');
    await expect(history).toHaveCSS('max-width', '670px');
    await page.screenshot({ path: info.outputPath(`group-history-${theme}.png`) });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(history.getByRole('button', { name: 'Close Group Transition History' })).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await expect(history.locator('.ui-badge--success')).toHaveText('Active Group');
    await page.keyboard.press('Escape');
    await expect(history).toHaveCount(0);
    await expect(dialog.getByRole('button', { name: 'Timeline', exact: true })).toBeFocused();
    await page.screenshot({ path: info.outputPath(`details-${theme}.png`) });
    await page.keyboard.press('Escape');
    await expect(roster).toBeFocused();
    await card.getByRole('button', { name: 'Session History', exact: true }).click();
    dialog = page.getByRole('dialog', { name: 'Session History', exact: true });
    await expect(dialog).toContainText('Latest: Oct 7, 2026');
    await expect(dialog.locator('.ui-badge--neutral')).toHaveCount(2);
    await expect(dialog.locator('.study-session-note')).toHaveCount(0);
    await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toHaveCount(0);
    await expect(dialog.getByText('Rows per page')).toHaveCount(0);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'More group actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Transitions Log', exact: true }).click();
    dialog = page.getByRole('dialog', { name: 'All Church Transitions & Merges Log', exact: true });
    await expect(dialog).toContainText('Reason: Group restructuring');
    await expect(dialog).toContainText('Merged from 2 groups');
    await expect(dialog.getByText('MERGED SOURCE', { exact: true })).toHaveCount(0);
    await expect(dialog.getByRole('button', { name: 'Inspect Group', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath(`transitions-${theme}.png`) });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(dialog.getByRole('button', { name: 'Close All Church Transitions & Merges Log' })).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.keyboard.press('Escape');
    await roster.click();
    dialog = page.getByRole('dialog', { name: group.name, exact: true });
    await expect(dialog.getByRole('button', { name: 'More group detail actions' })).toBeInViewport();
    await page.screenshot({ path: info.outputPath(`details-mobile-${theme}.png`) });
    await dialog.getByRole('button', { name: `Close ${group.name}` }).focus();
    await page.keyboard.press('Shift+Tab');
    await expect(dialog.getByRole('button', { name: 'More group detail actions' })).toBeFocused();
    await page.keyboard.press('Escape');
    expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden');
    await roster.click();
    await page.locator('.shared-modal-backdrop').click({ position: { x: 2, y: 2 } });
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(roster).toBeFocused();
    expect(mutations).toEqual([]);
    expect(errors).toEqual([]);
    await page.getByLabel('Appearance', { exact: true }).selectOption(theme === 'light' ? 'dark' : 'light');
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme === 'light' ? 'dark' : 'light');
    await expect(card).toHaveCSS('background-color', theme === 'light' ? 'rgb(17, 26, 44)' : 'rgb(255, 255, 255)');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await roster.click();
    await expect(page.getByRole('dialog', { name: group.name, exact: true })).toHaveCSS('animation-name', 'none');
  });
}
