import { test, expect } from '@playwright/test';

for (const theme of ['light', 'dark']) test(`book activities persist and filter progress choices (${theme})`, async ({ page }, info) => {
  const topic = { id: 1, title: 'Discussion Study', total_chapters: 12, has_discussion: true, has_review: true, has_exam: true };
  const group = { id: 11, name: 'Activity Test Group', status: 'active', curriculum: topic.title, curriculum_total_chapters: 12,
    current_chapter: 'Chapter 3', progress_stage: 'intro', leader_name: 'Test Admin', members: [], max_capacity: 12, category: 'General', meeting_day: 'Wednesday', meeting_time: '7:00 PM', location: 'Hall' };
  const saves: any[] = [];
  await page.addInitScript(theme => {
    sessionStorage.setItem('dpc_intro_shown', 'true'); localStorage.setItem('dpc_theme_mode', theme);
    localStorage.setItem('dpc_help_welcome_v1:1:Admin', 'seen');
    localStorage.setItem('chms_token', 'e30.' + btoa(JSON.stringify({ exp: 4102444800 })) + '.test');
  }, theme);
  await page.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname;
    let json: any = [];
    if (path.endsWith('/auth/setup-status')) json = { hasUsers: true, hasAdmin: true };
    else if (path.endsWith('/auth/me')) json = { user: { id: 1, name: 'Test Admin', role_name: 'Admin', ministries: [] } };
    else if (path.endsWith('/study-topics/1') && route.request().method() === 'PUT') {
      const data = route.request().postDataJSON(); saves.push(data); Object.assign(topic, data); json = { message: 'Saved' };
    } else if (path.endsWith('/study-topics') && route.request().method() === 'POST') {
      saves.push(route.request().postDataJSON()); json = { id: 2, message: 'Saved' };
    } else if (path.endsWith('/study-topics/1')) json = { topic, all_groups: [group] };
    else if (path.endsWith('/study-topics')) json = { topics: [topic], total_count: 1 };
    else if (path.endsWith('/groups') || path.endsWith('/groups/mine')) json = [group];
    else if (path.endsWith('/groups/11/attendance')) json = { sessions: [], summary: {}, members: [] };
    else if (path.endsWith('/settings/general')) json = { settings: {}, list: [] };
    else if (path.endsWith('/notifications')) json = { items: [], unread_count: 0 };
    else if (path.endsWith('/reports/dashboard')) json = { metrics: {}, ministry_breakdown: [] };
    else if (path.endsWith('/members/birthdays')) json = { celebrants: [], counts: {} };
    else if (path.endsWith('/members/baptism-candidates/qualified')) json = { candidates: [], counts: {} };
    else if (path.endsWith('/dishwashing/schedule')) json = { schedule: [] };
    await route.fulfill({ json });
  });
  await page.goto('/');
  await page.locator('aside').getByTitle('Curriculum Books/Topics', { exact: true }).click();
  await page.locator('[data-guide="curriculum-new"]').first().click();
  await expect(page.getByRole('checkbox', { name: 'Discussion & Reflection', exact: true })).toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true })).not.toBeChecked();
  await page.getByLabel('Book / Study Title *', { exact: true }).fill('Review Study');
  await page.getByRole('checkbox', { name: 'Discussion & Reflection', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Add Book to Curriculum', exact: true }).click();
  await expect.poll(() => saves.length).toBe(1);
  expect(saves[0]).toMatchObject({ has_discussion: false, has_review: true, has_exam: false });
  await page.getByRole('button', { name: 'Edit Discussion Study', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true }).uncheck();
  await page.getByRole('checkbox', { name: 'Review / Q&A', exact: true }).uncheck();
  await page.screenshot({ path: info.outputPath('book-stage-options.png') });
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  await expect.poll(() => saves.length).toBe(2);
  expect(saves[1]).toMatchObject({ has_discussion: true, has_review: false, has_exam: false });
  await page.getByRole('button', { name: 'Edit Discussion Study', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true })).not.toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'Review / Q&A', exact: true })).not.toBeChecked();
  await page.getByRole('button', { name: 'Close book form', exact: true }).click();
  const inspector = page.getByRole('complementary', { name: 'Book of Study details' });
  await inspector.getByRole('button', { name: 'Edit Book', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true })).not.toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'Review / Q&A', exact: true })).not.toBeChecked();
  await page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true }).check();
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  await inspector.getByRole('button', { name: 'Edit Book', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true })).toBeChecked();
  await page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Discussion Study', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Exam / Assessment', exact: true })).not.toBeChecked();
  await page.getByRole('button', { name: 'Close book form', exact: true }).click();
  await page.locator('aside').getByTitle('My Bible Study Group', { exact: true }).click();
  await page.locator('[data-guide="my-group-meetings"]').click();
  await page.getByRole('button', { name: 'Update Progress & Schedule', exact: true }).click();
  const stage = page.getByLabel('Study progress stage');
  await expect(stage.locator('option[value="application"]')).toHaveCount(1);
  await expect(stage.locator('option[value="review"]')).toHaveCount(0);
  await expect(stage.locator('option[value="exam"]')).toHaveCount(0);
  await expect(stage.locator('option[value="chapter_completed"]')).toHaveCount(1);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Take Weekly Roll-Call', exact: true }).click();
  await expect(stage.locator('option[value="application"]')).toHaveCount(1);
  await expect(stage.locator('option[value="exam"]')).toHaveCount(0);
  await expect(stage.locator('option[value="review"]')).toHaveCount(0);
  await expect(stage.locator('option[value="chapter_completed"]')).toHaveCount(1);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  group.progress_stage = 'exam';
  await page.reload();
  await page.locator('aside').getByTitle('My Bible Study Group', { exact: true }).click();
  await page.locator('[data-guide="my-group-meetings"]').click();
  await page.getByRole('button', { name: 'Update Progress & Schedule', exact: true }).click();
  await expect(stage).toHaveValue('exam');
  await expect(stage.locator('option[value="exam"]')).toHaveText('Exam / Assessment (recorded)');
  await page.getByLabel('Chapter / Lesson').selectOption('Chapter 4');
  await expect(stage.locator('option[value="exam"]')).toHaveCount(0);
});
