import type { NavTab } from "../layout/Sidebar";
import { taskGuides, type GuideStep, type TaskGuide } from "./guideContent";

const managers = ["Admin", "IT Admin", "Pastor", "Coordinator"];
const everyone = [...managers, "Leader", "Volunteer", "Member"];
const leaders = [...managers, "Leader"];
const attendanceRoles = [...managers, "Volunteer"];
const rootAdmins = ["Admin", "IT Admin"];
const accountManagers = ["Admin", "IT Admin", "Pastor"];
const s = (title: string, target: string, text: string, options: Partial<GuideStep> = {}): GuideStep => ({
  title, target, text, missing: "Open the indicated section first. If it is empty, create or select the record described in this step, then continue.", ...options,
});
const task = (id: string, title: string, tab: NavTab, roles: string[], description: string, steps: GuideStep[]): TaskGuide => ({ id, title, tab, roles, description, steps });

const batchSteps: GuideStep[] = [
  s("Confirm the service date", "attendance-service", "Select today's or a past Sunday service. Upcoming services are preview only; Batch Roll Call cannot save them.", { reveal: "attendance-sunday" }),
  s("Set the ministry scope", "attendance-scope", "Choose All Church or a ministry. This scope determines everyone included when you save the roll call.", { details: ["Confirm the service and ministry before selecting people.", "Changing service or ministry clears the current selections."] }),
  s("Enter Batch Roll Call", "attendance-batch", "Choose Batch Roll Call to display the methods, checkboxes, selection tools, and save summary.", { details: ["Choose Next step to open the batch controls.", "Entering or exiting batch mode resets the selected members."] }),
  s("Method 1: mark absentees", "attendance-method-absent", "Mark Absentees (Exception): select the people who are absent. Every unselected member in the scope will be marked Present.", { reveal: ["attendance-sunday", "attendance-batch"], missing: "Choose an editable Sunday service, then open Batch Roll Call.", details: ["Use this when most people attended.", "The guide highlights each method without changing your chosen method or selections."] }),
  s("Method 2: mark present attendees", "attendance-method-present", "Mark Present Attendees: select the people who attended. Every unselected member in the scope will be marked Absent.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Use this when you have a list of attendees.", "Changing the roll call method clears the selection; choose your method before checking names."] }),
  s("Method 3: selected present only", "attendance-method-selected", "Mark Selected Present Only: mark the selected people Present and leave every unselected member's existing status unchanged.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Use this to add late arrivals or record a few attendees without replacing the rest of the roster."] }),
  s("Find people and families", "attendance-search", "Search inside the roll call toolbar by member name. Use the household dropdown to work through one family at a time.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Search and household filters narrow the visible rows, not the ministry scope that Save Roll Call applies to.", "Selections remain when you change the search, so review the selected count."] }),
  s("Use the selection tools", "attendance-selection-tools", "Select All selects the currently filtered rows. Clear removes selections; Invert switches the selection for the visible rows.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Use the row checkboxes for individual members.", "Check the count of selected members against the total in scope."] }),
  s("Review the row targets", "attendance-roster", "Check Roll Call Target for each row: Will Mark Absent, Will Mark Present, or unchanged, according to your method and selection.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Existing Attendance Status and the proposed Roll Call Target are different columns.", "Review the full scope, including rows hidden by your current search."] }),
  s("Save and verify the roll call", "attendance-batch-save", "Check the Absent/Present totals on Save Roll Call, then choose it to apply the batch. Save Attendance Changes in the floating bar performs the same save.", { reveal: ["attendance-sunday", "attendance-batch"], details: ["Next step and Finish guide never save attendance.", "Wait for confirmation and verify the updated statuses. Reset or Exit Batch Roll Call discards unsaved selections."] }),
];

export const workflowGuides: TaskGuide[] = [
  task("assign-group", "Assign a Bible study group to an account", "biblestudy", managers, "Link the correct leader or disciple so their personal group page becomes available.", [
    s("Find the intended group", "groups-search", "Search for the existing Bible study group. Check its ministry and status before changing its assignments."),
    s("Review the group", "group-details", "Open the intended group's details and check its current leader and disciples. Create a group first if the church has not set one up.", { missing: "Create a Bible study group or clear the directory filters first." }),
    s("Open group editing", "group-edit", "Choose Edit in the selected group's details. Confirm the group name before changing anyone's assignment.", { missing: "Open the intended group from the directory to see Edit." }),
    s("Assign its leader", "group-leader", "Select the permitted leader account or linked member. Use the correct account or member record so My Bible Study Group can identify the assignment.", { reveal: "group-edit", details: ["Check the person's account and linked member record in User Management when necessary.", "Entering an unrelated custom name alone may not link the person to their sign-in account."] }),
    s("Enroll its disciples", "group-members", "Select the church members who belong to this group. For a member account, check that it is linked to the enrolled member record.", { reveal: "group-edit" }),
    s("Save and refresh assignments", "group-save", "Review and save the group changes yourself. Return to the original personal group guide and refresh assignments to check that the group is now available.", { reveal: "group-edit" }),
  ]),
  task("batch-attendance", "Use Sunday Batch Roll Call", "attendance", attendanceRoles, "All three methods, ministry scope, family filters, selections, and saving.", batchSteps),
  task("attendance-actions", "Mark attendance, excuse, or check out a child", "attendance", attendanceRoles, "Individual status actions, reasons, corrections, and child pickup verification.", [
    batchSteps[0],
    s("Find the intended member", "attendance-search", "Search for the person's full name and confirm their ministry and household. Exit Batch Roll Call to use individual row actions.", { reveal: "attendance-sunday" }),
    s("Mark Present or Check In", "attendance-present", "Choose Present for an adult or Check In for a child on the intended row. Wait for confirmation and check the status and security tag.", { details: ["This action records attendance when you choose it; the guide does not choose a person or mark attendance."] }),
    s("Mark Absent or Excused", "attendance-excused", "Use Absent for a quick absence, or Excused to enter a reason. Confirm the intended person's name in the reason form."),
    s("Review the reason and save", "attendance-reason-form", "Choose the appropriate status and preset reason, add notes when necessary, then save. Check the resulting attendance status.", { missing: "Choose Excused on the intended person's row to open the reason form." }),
    s("Verify a child's checkout", "attendance-checkout", "After closing the reason form, use the checked-in child's checkout action. Confirm the child's name and household before entering the pickup code.", { missing: "Check in a child first. The checkout action appears on their checked-in row." }),
    s("Confirm pickup and corrections", "attendance-checkout-form", "Enter the pickup/security code and use Verify Code. Check the result. Use any permitted force checkout only after reviewing the child and pickup details.", { missing: "Open checkout for the intended checked-in child first.", details: ["For an accidental attendance mark, use the row's Undo action and verify the corrected status."] }),
  ]),
  task("event-attendance", "Record special event attendance", "attendance", attendanceRoles, "Choose an event, handle walk-ins, and record individual or batch attendance.", [
    s("Open special event check-in", "attendance-event", "Choose Special Event Check-In. Its attendance is separate from Sunday worship."),
    s("Choose the event", "event-attendance-event", "Select the event you are recording. Check its date and registration list before marking attendance.", { reveal: "attendance-event" }),
    s("Find an attendee", "event-attendance-search", "Search by attendee name or phone and use the status filters to find unmarked registrations.", { reveal: "attendance-event" }),
    s("Add a walk-in", "event-attendance-walkin", "Use Add Walk-In for an existing church member who is absent from the registration list. Search the member and choose Add yourself.", { reveal: "attendance-event", details: ["Adding the walk-in records an attendance change; it is not performed by the guide."] }),
    s("Open event batch mode", "event-attendance-batch", "For a large event, choose Batch Roll Call to select several attendees together.", { reveal: "attendance-event" }),
    s("Choose the batch method", "event-attendance-methods", "Absentees: selected absent, the rest present. Present Attendees: selected present, the rest absent. Selected Present Only: selected present, the rest unchanged.", { reveal: ["attendance-event", "event-attendance-batch"], details: ["Changing method clears selections. Search filters visible rows; the save applies to the event's batch scope."] }),
    s("Review and save event attendance", "event-attendance-save", "Review the selected rows and proposed totals, then choose Save Roll Call. Wait for confirmation and verify the attendee statuses.", { reveal: ["attendance-event", "event-attendance-batch"] }),
  ]),
  task("guest-checkin", "Check in a Sunday guest", "attendance", attendanceRoles, "Register a visitor on the correct service and verify check-in.", [
    batchSteps[0],
    s("Open the guest form", "attendance-guest", "Choose the guest registration control for a visitor without a member record."),
    s("Enter guest details", "attendance-guest-form", "Enter the guest's first and last names, ministry, phone, and any notes. Confirm the selected service before submitting.", { reveal: ["attendance-sunday", "attendance-guest"] }),
    s("Register and verify", "attendance-guest-form", "Review the details and submit the guest form yourself. Wait for confirmation, then find the guest on the service roster.", { details: ["For an existing member, close this form and use the roster instead of creating a duplicate."] }),
  ]),
  task("household", "Create or update a household", "members", managers, "Address, father and mother, children, relatives, and application links.", [
    s("Find the household first", "households-tab", "Open Households and check whether the family already has a household. Use Edit Household & Family on that card to update it."),
    s("Create a household", "household-create", "Choose New Household for a new family. Use the existing household's Edit action for corrections."),
    s("Name and address", "household-name", "Enter a recognizable household name, then its shared address and emergency contact phone.", { reveal: "household-create", details: ["Use the structured address selector or Type Manually for the address."] }),
    s("Set father and mother", "household-parents", "Select a registered household member or type each parent's full name. A parent does not need a church member record.", { reveal: "household-create", details: ["Father and Mother are separate fields; leave an unavailable parent empty.", "The application uses the father first, then the mother when no father is available."] }),
    s("Add children and relatives", "household-family", "Use Add Family Member for each child or relative. Enter their name and relationship, or link their church member record.", { reveal: "household-create", details: ["Check the relationship on every row and remove accidental duplicates.", "These family details reflect in applications linked to this household."] }),
    s("Save the household", "household-save", "Review the parents, contact, and family rows, then choose Create Household or Save Household. Check the updated household card after confirmation.", { reveal: "household-create" }),
  ]),
  task("application-family", "Link a member's household and family", "members", managers, "Use the household's parents or guardian and family members on an application.", [
    s("Open the member application", "member-add", "Choose Add Member, or find the existing member and choose Edit in their profile."),
    s("Enter name and birthday", "member-name", "Enter the full name and date of birth first so the application shows the appropriate ministry fields.", { reveal: "member-add" }),
    s("Select the household", "member-household", "Choose Select List and the member's existing household, then choose their relationship in the family, such as Son, Daughter, Grandfather, or Grandmother.", { reveal: "member-add" }),
    s("Check parents or guardian", "member-guardian", "Review Name of parents or guardian (relatives). The linked household supplies the father, or the mother if no father is entered, with the guardian where applicable.", { reveal: "member-add", details: ["Check the guardian name and contact number when those fields appear.", "Edit the household if the shared parent information needs correction."] }),
    s("Check family members", "member-family", "Review the reflected family details from the linked household. Linked summaries are read-only; maintain family rows in Edit Household & Family.", { reveal: "member-add" }),
    s("Review and save the application", "member-save", "Complete the remaining required fields and save the application yourself. Reopen the profile to verify its household and parent details.", { reveal: "member-add" }),
  ]),
  task("import-members", "Import member forms or a file", "members", managers, "Upload or paste, review detected records, resolve issues, and save.", [
    s("Open import", "member-import", "Choose Import Form / File to analyze member applications or a list."),
    s("Upload the source", "import-file", "Choose your file using the upload control. Wait for the analysis before proceeding.", { reveal: "member-import", details: ["Check the supported formats shown in this window."] }),
    s("Or paste text", "import-paste", "Use the paste option when you have copied application text. Review the pasted contents and run its analysis yourself.", { reveal: "member-import" }),
    s("Review detected members", "import-results", "Search the detected records and inspect each proposed name, birthday, ministry, household, and required-field issue.", { missing: "Upload or analyze pasted text first to display the detected members.", details: ["Resolve duplicates and incomplete details before selecting records for import.", "Check that the selected count matches the records you want to save."] }),
    s("Save reviewed records", "import-save", "Use the import save control only after reviewing the selected records. Wait for the result and check the saved members in the directory.", { missing: "Analyze the source and select valid records first. The save control appears with the results." }),
  ]),
  task("attendance-history", "Filter and export attendance history", "attendancelog", attendanceRoles, "Date range, service type, status, ministry or group, and CSV/PDF export.", [
    s("Choose the starting date", "log-from", "Set From to the first day of the attendance period you need."),
    s("Choose the ending date", "log-to", "Set To to the last day. Use a range that includes the service or group meeting you are investigating."),
    s("Choose attendance type", "log-type", "Choose Sunday Worship Service, Bible Study / Small Group, Special Event, or All Types."),
    s("Narrow the records", "log-status", "Choose Present, Absent, Excused, or All Statuses. Then set the ministry and group filters when available.", { details: ["A group filter is useful for Bible study session records."] }),
    s("Find a member", "log-search", "Search by first or last name and inspect the matching service dates, attendance statuses, and notes.", { details: ["Use the table pagination to inspect further results.", "Reset Filters clears the current search and filter selections."] }),
    s("Export CSV", "log-csv", "Choose the CSV export to download the filtered records for spreadsheet review."),
    s("Export PDF", "log-pdf", "Choose the PDF export for a shareable attendance report. Check the date range and filters before exporting."),
  ]),
  task("service-create", "Create a worship service", "servicecalendar", managers, "Set the service date, type, title, availability, and notes.", [
    s("Check existing dates", "service-list", "Use List or Month view to check whether this worship service already exists."),
    s("Open a new service", "service-new", "Choose New Service to set up a service date."),
    s("Set the service date", "service-date", "Choose the actual worship date; Sunday worship and special services use their own service types.", { reveal: "service-new" }),
    s("Choose service type", "service-type", "Select Sunday Worship Service or Special Service. Set a clear service title and confirm the status.", { reveal: "service-new" }),
    s("Add notes", "service-notes", "Add service-specific instructions or the reason for cancellation when relevant.", { reveal: "service-new" }),
    s("Save and verify availability", "service-save", "Review the date, title, type, and status, then save. Verify the service appears on the calendar before recording its attendance.", { reveal: "service-new" }),
  ]),
  task("group-progress", "Update a group's study progress", "biblestudy", managers, "Select the group, update chapters and notes, and verify history.", [
    s("Find the active group", "groups-search", "Search by topic, leader, location, or group name. Confirm you are viewing Active groups."),
    s("Open group details", "group-details", "Open the intended group's details and confirm its leader, disciples, and curriculum.", { missing: "Create a group or adjust the filters if no group appears." }),
    s("Open study progress", "group-progress", "Choose the progress action for the selected group.", { missing: "Select a group from the directory first." }),
    s("Record chapters and notes", "group-progress-form", "Enter the current chapter and progress notes. Keep the chapter within the curriculum's total, then submit the progress update.", { reveal: "group-progress", missing: "Open a group's details and choose its progress action first." }),
    s("Verify group history", "group-history", "After saving, close the progress form and open History to check the recorded study update."),
  ]),
  task("group-lifecycle", "Complete, archive, or transition a group", "biblestudy", managers, "Understand study completion, archival, history, and ministry transitions.", [
    s("Review group status", "groups-status", "Switch between Active, Completed, Archived, and All. Find the intended group before changing its lifecycle."),
    s("Inspect history", "group-history", "Use History to check past study progress and changes before completing or archiving the group."),
    s("Complete a study", "group-complete", "Use the group's completion action when it has finished its curriculum. Review the book, chapter totals, and completion notes in the confirmation form.", { details: ["Completion preserves a study snapshot; confirm it using the form yourself."] }),
    s("Archive a group", "group-archive", "Use Archive for a group that should leave the active directory. Enter the reason and confirm only the intended group.", { details: ["Archived groups remain available in the Archived list with their history."] }),
    s("Review ministry transitions", "group-transition", "Open the transition tool for age or ministry changes. Review the affected groups and members before applying any reassignment."),
  ]),
  task("group-reschedule", "Reschedule a Bible study meeting", "biblestudy", managers, "One-session changes, room availability, reasons, and optional leader notification.", [
    s("Find the group", "groups-search", "Search the group and confirm its current leader, regular meeting schedule, and location."),
    s("Open rescheduling", "group-reschedule", "Choose the intended group's reschedule action. Check that the form shows the correct group."),
    s("Choose the scheduling action", "group-reschedule-kind", "Choose to reschedule a session or return to the original schedule. Review the original date and location shown by the form.", { missing: "Open Reschedule for the intended group first." }),
    s("Set the replacement date and time", "group-reschedule-date", "Choose the replacement meeting date and start/end times. Review the room availability display and choose an available church room or a custom location.", { missing: "Choose Reschedule Session in the group's rescheduling form to show the replacement date." }),
    s("Explain the change", "group-reschedule-reason", "Choose a reason preset or write the scheduling reason. Review the replacement date, times, room, and any conflict message."),
    s("Save with or without notification", "group-reschedule-save", "Use the save action to record the change. If you want the leader notified, use Save & Notify Leader instead and review the result.", { details: ["The notification action sends a message only when you choose it.", "After saving, check the group schedule and history for the changed session."] }),
  ]),
  task("curriculum-create", "Add a book or study topic", "curriculum", leaders, "Title, lesson count, study notes, saving, and inspector.", [
    s("Search existing study material", "curriculum-search", "Search the book title or notes first to avoid duplicate topics."),
    s("Open a new topic", "curriculum-new", "Choose the new study-topic control."),
    s("Enter the book title", "curriculum-title", "Enter a clear title that leaders will recognize when selecting group curriculum.", { reveal: "curriculum-new" }),
    s("Set total lessons", "curriculum-lessons", "Enter the total chapters or lessons used by this study. Group progress is measured against this total.", { reveal: "curriculum-new" }),
    s("Add study notes", "curriculum-notes", "Write the summary, study focus, or instructions needed by the group leaders.", { reveal: "curriculum-new" }),
    s("Save and check the inspector", "curriculum-save", "Review and save the topic. Find it in the list and open its inspector to verify the title, lessons, notes, and linked groups.", { reveal: "curriculum-new" }),
  ]),
  task("calendar-explore", "Find and inspect calendar activities", "events", everyone, "Month or agenda, activity types, ministry filters, and activity details.", [
    s("Choose calendar view", "calendar-view", "Use Calendar for the month layout. Use previous, next, or Today to reach the date you need."),
    s("Choose activity types", "calendar-kinds", "Filter church events, Saturday duty, Bible study, or birthdays. Clear a restrictive type filter if an activity is missing."),
    s("Search the activity", "calendar-search", "Search by title, team, leader, or location and choose a ministry when the filter is available."),
    s("Try agenda view", "calendar-agenda", "Agenda lists activities chronologically and makes it easier to inspect a busy schedule."),
    s("Open an activity", "calendar-inspect", "Choose the intended activity to display its inspector. Confirm the date, time, place, responsible people, and notes.", { reveal: "calendar-agenda", missing: "Add or schedule an activity, or adjust the month and filters to show existing activities." }),
    s("Use the relevant action", "calendar-details", "The inspector's actions depend on the activity type and your role. For an event, review registration or attendance controls; for duty or Bible study, follow its related page.", { details: ["RSVP or registration actions change your participation only when you choose them.", "Create Event opens Events & Celebrations to set up the event."] }),
  ]),
  task("celebration-create", "Create an event or annual celebration", "sundaycycle", managers, "Recurring versus one-time, dates, location, saving, and calendar scheduling.", [
    s("Check the year and existing events", "celebration-year", "Choose the year and search the celebration first. Use type or quarter filters to narrow the cards."),
    s("Open event setup", "celebration-new", "Choose the add event control for a new celebration."),
    s("Choose the event kind", "celebration-kind", "Choose an annually recurring event or a one-time event. Recurring events use a yearly date rule; one-time events use a specific date.", { reveal: "celebration-new" }),
    s("Enter title and schedule", "celebration-title", "Enter the event name, theme, date or recurrence rule, and other required scheduling information.", { reveal: "celebration-new" }),
    s("Set the location and instructions", "celebration-location", "Choose or enter the venue and include the event instructions so the calendar entry is useful.", { reveal: "celebration-new" }),
    s("Save the celebration", "celebration-save", "Review its kind, year, date rule, venue, and instructions, then save. Check the resulting celebration card.", { reveal: "celebration-new" }),
    s("Schedule it on the calendar", "celebration-sync", "Close the setup form after saving and use the intended event's calendar scheduling control. Review the proposed date and attendance settings.", { missing: "Save an event first, then choose its calendar scheduling action." }),
    s("Confirm calendar scheduling", "celebration-sync-save", "Check the proposed calendar entry before choosing the scheduling confirmation. Verify it on Calendar afterward.", { missing: "Open the saved event's calendar scheduling dialog first." }),
  ]),
  task("duty-team", "Create a Saturday duty team", "duty", managers, "Team name, rotation order, leader, members, and responsibilities.", [
    s("Check duty teams", "duty-teams", "Check existing teams before creating a new one.", { reveal: "duty-teams-tab" }),
    s("Open team setup", "duty-new", "Choose the new team action."),
    s("Name the team and order", "duty-team-name", "Enter the team name and rotation order. The order determines its place in the Saturday cycle.", { reveal: "duty-new" }),
    s("Assign the leader", "duty-team-leader", "Select the church member who will coordinate this team's service.", { reveal: "duty-new" }),
    s("Select team members", "duty-team-members", "Open Select Members, search or filter by ministry, and check the people to include. Apply the selection to return to the team form.", { reveal: "duty-new" }),
    s("Set responsibilities", "duty-team-tasks", "Review the team member list and enter the team's tasks or preparation instructions.", { reveal: "duty-new" }),
    s("Save the team", "duty-team-save", "Review leader, members, tasks, and rotation order, then save. Check its team card and upcoming Saturday assignments.", { reveal: "duty-new" }),
  ]),
  task("duty-swap", "Swap Saturday duty dates", "duty", managers, "Choose two dates, review assignments, and confirm the swap.", [
    s("Review the current rotation", "duty-schedule", "Check the assigned teams and dates before arranging a swap.", { reveal: "duty-schedule-tab" }),
    s("Choose a swap action", "duty-swap", "Use Swap on the intended duty date. Confirm that the source team and date are correct."),
    s("Choose the other Saturday", "duty-swap-form", "Select the other Saturday in the swap dropdown. Check both team/date assignments before confirming.", { missing: "Open Swap for the intended Saturday first." }),
    s("Confirm and verify", "duty-swap-form", "Confirm the swap yourself, wait for success, and inspect both dates in the rotation. Add any coordination notes required by the form."),
  ]),
  task("duty-checklists", "Manage cleaning tasks and guidelines", "duty", managers, "Maintain the common checklist and preparation guidelines.", [
    s("Open tasks and guidelines", "duty-checklist-tab", "Open the cleaning checklist and guideline section."),
    s("Add a cleaning task", "duty-task-new", "Choose Add Task. Enter the task and its description, then review before saving.", { reveal: "duty-checklist-tab" }),
    s("Review the task form", "duty-task-form", "Write a concrete cleaning action and its completion instructions. Save the task yourself.", { reveal: ["duty-checklist-tab", "duty-task-new"] }),
    s("Add a guideline", "duty-guideline-new", "Close the task form and choose Add Guideline for preparation, equipment, or serving instructions.", { reveal: "duty-checklist-tab" }),
    s("Save the guideline", "duty-guideline-form", "Enter the guideline title and description, then save and check that it appears with the other guidelines.", { reveal: ["duty-checklist-tab", "duty-guideline-new"] }),
  ]),
  task("washing-team", "Create a dishwashing roster team", "dishwashing", managers, "Choose roster sources, leader, rotation order, and duties.", [
    s("Review roster teams", "washing-teams-tab", "Open Teams and check the current roster units before adding one."),
    s("Open roster setup", "washing-new", "Choose the new roster team control."),
    s("Choose the roster source", "washing-team-form", "Choose the team type offered in the form: Bible study group, ministry, combined unit, or custom team. Select the source groups or ministries.", { reveal: "washing-new" }),
    s("Set the name and order", "washing-team-name", "Review the roster name and rotation order after selecting its sources.", { reveal: "washing-new" }),
    s("Assign the roster lead", "washing-team-leader", "Choose the leader and check their contact information and volunteer count.", { reveal: "washing-new" }),
    s("Set washing responsibilities", "washing-team-tasks", "Enter the preparation and washing tasks that this unit is responsible for.", { reveal: "washing-new" }),
    s("Save and check Sundays", "washing-team-save", "Review and save the team. Check its assigned Sundays in the Sunday rotation after the save succeeds.", { reveal: "washing-new" }),
  ]),
  task("washing-swap", "Swap or override Sunday washing duty", "dishwashing", managers, "Change two assignments or adjust one Sunday's team, status, and notes.", [
    s("Review the Sunday rotation", "dishwashing-schedule", "Find the Sunday you need and confirm the assigned roster unit.", { reveal: "dishwashing-schedule-tab" }),
    s("Swap two Sundays", "washing-swap", "Use Swap for the intended Sunday, choose the second Sunday, and review both roster assignments before confirming."),
    s("Review the swap form", "washing-swap-form", "Confirm the source and target dates before executing the swap. Check both dates after the confirmation succeeds.", { missing: "Open Swap on the intended Sunday first." }),
    s("Override a single assignment", "washing-override", "Close the swap form and use Override on a schedule row to change that Sunday's roster unit, status, or notes.", { reveal: "dishwashing-schedule-tab" }),
    s("Review and save the override", "washing-override-form", "Select the intended team and status, enter the reason or notes, then save. Verify the changed Sunday assignment.", { missing: "Choose Override on a Sunday schedule row first." }),
  ]),
  task("washing-protocols", "Manage kitchen protocols and checklist", "dishwashing", managers, "Write washing procedures, their steps, and checklist tasks.", [
    s("Open kitchen tasks", "washing-protocols-tab", "Open the protocols and checklist section."),
    s("Add a protocol", "washing-protocol-new", "Choose Add Protocol for a reusable washing or sanitation procedure.", { reveal: "washing-protocols-tab" }),
    s("Write the protocol steps", "washing-protocol-form", "Enter the protocol title, subtitle, and ordered steps. Review the procedure and save it yourself.", { reveal: ["washing-protocols-tab", "washing-protocol-new"] }),
    s("Add a checklist task", "washing-checklist-new", "Close the protocol form and choose Add Task for an action that the crew should check off.", { reveal: "washing-protocols-tab" }),
    s("Save the checklist task", "washing-checklist-form", "Enter the task and its available instructions, save, then check the kitchen checklist.", { reveal: ["washing-protocols-tab", "washing-checklist-new"] }),
  ]),
  task("publish-announcement", "Publish a church announcement", "communications", managers, "Title, ministry audience, message, and publishing review.", [
    s("Check the announcements board", "announcements-list", "Check existing notices before publishing another announcement."),
    s("Open announcement setup", "announcement-new", "Choose the new announcement control."),
    s("Set the title", "announcement-title", "Write a specific title that identifies the subject or activity.", { reveal: "announcement-new" }),
    s("Choose the audience", "announcement-audience", "Choose the ministry audience or church-wide option available to your role.", { reveal: "announcement-new" }),
    s("Write the full message", "announcement-body", "Include the purpose, date, time, location, preparation, and contact person as appropriate.", { reveal: "announcement-new" }),
    s("Review and publish", "announcement-save", "Check title, audience, and message before publishing. Wait for success and verify the notice on the board.", { reveal: "announcement-new" }),
  ]),
  task("analytics", "Read and print analytics", "reports", managers, "Period selection, growth charts, demographics, birthdays, and printing.", [
    s("Choose the report period", "reports-period", "Choose 3 months, 6 months, 12 months, or year to date. The growth charts use this period."),
    s("Read growth and attendance", "reports-growth", "Review the growth and attendance charts. Check their date labels and totals before comparing periods."),
    s("Review demographics", "reports-demographics", "Switch to Demographics to inspect the ministry, age, or population summaries shown on this page."),
    s("Inspect birthdays by month", "reports-birthday-month", "Choose a month to inspect its celebrants. Choose it again to clear the selection.", { reveal: "reports-demographics" }),
    s("Print the report", "reports-print", "Choose Print Report after setting the period and report section. Review the print preview before printing or saving a PDF."),
  ]),
  task("user-create", "Create a user account and assign access", "users", accountManagers, "Identity, sign-in details, role, ministry scope, and verification.", [
    s("Check existing accounts", "users-search", "Search the person's name, email, or ministry before creating an account."),
    s("Open a new account", "users-new", "Choose the add account control. The roles you can assign depend on your own access."),
    s("Enter account identity", "users-name", "Enter the account holder's name and contact details.", { reveal: "users-new" }),
    s("Set sign-in details", "users-login", "Choose the username and enter the required password using the password field.", { reveal: "users-new" }),
    s("Choose the role", "users-role", "Select the role that matches the person's responsibilities. Review the role permissions instead of granting unnecessary access.", { reveal: "users-new" }),
    s("Assign ministry scope", "users-ministries", "Select the ministries this account may manage when the role uses ministry assignments.", { reveal: "users-new" }),
    s("Save and verify access", "users-save", "Review the role and ministry assignments, then save. Open the resulting account details to verify the access.", { reveal: "users-new" }),
  ]),
  task("user-review", "Review accounts and password reset", "users", accountManagers, "Role filters, permission matrix, account details, and reset confirmation.", [
    s("Find the account", "users-search", "Search the intended user and narrow the list with role filters."),
    s("Review role permissions", "users-matrix", "Open the permissions matrix to compare what each role can access."),
    s("Open account details", "users-details", "Select the intended account and check its role, ministries, and account status."),
    s("Start password reset", "users-reset-password", "Use Reset Password only for the intended account. Check the account name and your authority before continuing.", { missing: "Open an account's details first. Reset controls depend on your role and the target account." }),
    s("Complete the reset confirmation", "users-password-reset-form", "Provide the required administrator verification and review the reset details. Confirm the reset yourself and wait for its result.", { missing: "Use the intended account's password reset action first." }),
  ]),
  task("audit-review", "Inspect and export audit history", "audit", accountManagers, "Time and action filters, operator search, change details, and CSV export.", [
    s("Choose the time range", "audit-time", "Choose the timeframe containing the change you need to investigate."),
    s("Choose an action", "audit-actions", "Filter by the action type, or return to All to include all kinds of changes."),
    s("Find the operator or record", "audit-search", "Search by operator, action, table, or keywords. Check the timestamp, affected record, and operator on each result."),
    s("Set the sort order", "audit-sort", "Choose newest or oldest first to follow the order of changes."),
    s("Inspect a transaction", "audit-inspect", "Open the intended log entry to inspect its recorded change details and metadata.", { missing: "No matching history? Clear restrictive filters or choose a wider timeframe." }),
    s("Export the selected history", "audit-export", "Close the inspector after review, then use Export CSV for the filtered audit entries."),
  ]),
  task("church-settings", "Update church information", "settings", accountManagers, "Church name, address, contacts, worship details, and save verification.", [
    s("Open general settings", "settings-general", "Choose Church Profile & Config to review the church's identity and contact settings."),
    s("Update church identity", "settings-church-name", "Enter the church name and check the pastor, motto, and other identity fields.", { reveal: "settings-general" }),
    s("Review address and contacts", "settings-general-form", "Check address, phone, email, worship times, and the available system preferences.", { reveal: "settings-general" }),
    s("Save general settings", "settings-general-save", "Review the values, save, and wait for confirmation. Recheck the updated church details afterward.", { reveal: "settings-general" }),
  ]),
  task("reference-settings", "Manage ministries and reference lists", "settings", accountManagers, "Age ranges, ministry colors, categories, venues, and membership statuses.", [
    s("Review ministries", "settings-ministries", "Open Ministries to review the age ranges and names used for member assignments."),
    s("Add or edit a ministry", "settings-ministry-new", "Choose Add Ministry or edit the intended ministry. Check the name, age bounds, and color.", { reveal: "settings-ministries" }),
    s("Review ministry settings", "settings-ministry-form", "Enter the required ministry information and check the age range before saving.", { reveal: ["settings-ministries", "settings-ministry-new"] }),
    s("Save the ministry", "settings-ministry-save", "Save the intended ministry and verify its age range in the list.", { reveal: ["settings-ministries", "settings-ministry-new"] }),
    s("Choose a reference list", "settings-bible_study_categories", "Close the ministry form and choose the relevant settings tab: study categories, locations, events, communications, or membership."),
    s("Add or edit a reference entry", "settings-lookups-new", "Choose Add in the selected list, or edit its intended row. Complete the name, description, color, order, and active status offered by that list."),
    s("Save the reference entry", "settings-lookup-save", "Review and save the entry. Check that it appears in the correct list and is available where it is used.", { missing: "Open Add or Edit in the intended reference list first." }),
  ]),
  task("email-settings", "Configure notification email", "settings", accountManagers, "SMTP, sender, notification rules, saving, and a test email.", [
    s("Open email settings", "settings-notifications_email", "Choose Notifications & Email to review email delivery configuration."),
    s("Configure delivery and rules", "settings-email-form", "Check sender identity, SMTP host and port, login details, recipients, and notification rules.", { reveal: "settings-notifications_email", details: ["Keep the provider's required port and security configuration consistent."] }),
    s("Save email settings", "settings-email-save", "Save the reviewed configuration. Use Send test email yourself to check delivery and inspect its success or error message.", { reveal: "settings-notifications_email" }),
  ]),
  task("backup", "Back up or restore church data", "settings", rootAdmins, "Choose backup scope, review restore input, and understand yearly deletion.", [
    s("Open backup and restore", "settings-backup_restore", "Choose Backup & Restore to review the data maintenance tools."),
    s("Create a backup", "backup-create", "Choose the backup years or scope, review the preview, and use the backup download action. Keep the downloaded backup for recovery.", { reveal: "settings-backup_restore" }),
    s("Review a restore file", "backup-restore", "Choose the intended backup file, review the detected contents and restore options, and read the confirmation before applying the restore.", { reveal: "settings-backup_restore", details: ["Check the scope and effect described by the restore confirmation before executing it."] }),
    s("Review yearly deletion", "backup-purge", "Select the intended year and inspect the affected-record preview. Execute deletion only after reviewing its confirmation.", { reveal: "settings-backup_restore" }),
    s("Inspect cloud synchronization", "backup-cloud", "Open cloud sync to review its connection and sync options. Check the source and destination before choosing a push or pull action.", { reveal: "settings-backup_restore" }),
  ]),
  task("backup-download", "Create and download a database backup", "settings", rootAdmins, "Select years, inspect the included tables, verify authorization, and download.", [
    s("Open backup tools", "settings-backup_restore", "Choose Backup & Data Management."),
    s("Choose the backup scope", "backup-scope", "Choose Full Database or the intended year. Check its record count before opening the backup preview.", { reveal: "settings-backup_restore" }),
    s("Open the backup preview", "backup-open", "Open the backup dialog for the chosen scope. It shows the data included in the download.", { reveal: "settings-backup_restore" }),
    s("Inspect included tables", "backup-preview-tabs", "Review the preview tabs and table rows to confirm the intended records are included.", { reveal: ["settings-backup_restore", "backup-open"] }),
    s("Verify authorization", "backup-auth", "Enter the administrator password required by the backup form and recheck its scope.", { reveal: ["settings-backup_restore", "backup-open"] }),
    s("Download the backup", "backup-download", "Choose the download confirmation yourself. Wait for the backup file and keep it in your chosen recovery location.", { reveal: ["settings-backup_restore", "backup-open"] }),
  ]),
  task("restore-data", "Review and restore a backup file", "settings", rootAdmins, "File validation, replace or merge mode, confirmation, and restore result.", [
    s("Open restore tools", "settings-backup_restore", "Choose Backup & Data Management and review the restore section."),
    s("Choose the backup file", "restore-file", "Open Restore and select the intended .json backup. Wait for validation and check the backup type, table counts, and total records.", { reveal: ["settings-backup_restore", "restore-open"] }),
    s("Choose restore mode", "restore-mode", "Review Replace versus Merge and choose the appropriate mode using the effect described in the dialog.", { missing: "Upload a valid backup file to display its restore mode options." }),
    s("Review confirmation and authorization", "restore-confirmation", "Check the validated backup scope. Enter the requested confirmation text when shown and the administrator password.", { missing: "Validate the backup file and review the restore mode first." }),
    s("Execute and verify restore", "restore-execute", "Use the restore confirmation only after checking the file, mode, counts, and authorization. Wait for completion and verify the restored records.", { missing: "Upload and validate a backup file first." }),
  ]),
  task("purge-year", "Review yearly record deletion", "settings", rootAdmins, "Select a year, inspect affected records, and review deletion authorization.", [
    s("Open data maintenance", "settings-backup_restore", "Choose Backup & Data Management and review yearly data maintenance."),
    s("Expand historical records", "backup-purge", "Expand Delete historical records to show the year selector and deletion preview action.", { reveal: "settings-backup_restore" }),
    s("Choose the intended year", "purge-year", "Select the year to inspect. Check its affected-record count and keep a backup before deleting records.", { reveal: "settings-backup_restore", missing: "Expand Delete historical records to select a year. Annual activity must exist before deletion is available." }),
    s("Inspect the deletion preview", "purge-open", "Open the selected year's deletion preview and inspect the affected tables and record counts. Confirm that it is the intended year."),
    s("Review required authorization", "purge-confirmation", "Read the deletion confirmation and enter the requested year and password authorization only after inspecting the preview.", { missing: "Open the deletion preview for the intended year first." }),
    s("Confirm and verify deletion", "purge-execute", "Choose the final deletion action yourself after reviewing its effect. Wait for completion and check the year-by-year registry.", { missing: "Open the intended year's deletion dialog first." }),
  ]),
  task("notifications", "Review and organize notifications", "notifications", accountManagers, "Unread view, related records, and read controls.", [
    s("Review all notifications", "notifications-all", "Use All to inspect notifications regardless of read status."),
    s("Focus on unread alerts", "notifications-unread", "Use Unread to see alerts still needing your attention."),
    s("Open the related record", "notifications-open", "Read the intended notification and choose it to open its related group, event, or record. Opening an alert can mark it read.", { missing: "There are no matching notifications. Choose All to include read alerts." }),
    s("Change read status", "notifications-read", "Use the individual read/unread control to organize the list. Mark All Read applies to the whole current notification collection.", { missing: "Read controls appear on notification rows when there are notifications." }),
  ]),
  task("profile", "Update my profile and password", "profile", everyone, "Personal details, password, role permissions, and account activity.", [
    s("Review personal information", "profile-personal", "Open Personal Information and check your name and contact details."),
    s("Edit and save personal details", "profile-form", "Update the editable fields and use Save Changes. Wait for the success message before switching sections.", { reveal: "profile-personal" }),
    s("Open account security", "profile-security", "Choose Account Security to change your password."),
    s("Set a new password", "profile-password-form", "Enter your current password, the new password, and its confirmation. Review the requirements and submit the password change yourself.", { reveal: "profile-security" }),
    s("Review your access", "profile-roles", "Use Roles & Permissions to check your role and ministry scope."),
    s("Inspect account activity", "profile-activity", "Use Activity to review the account's recorded activity and recent changes."),
  ]),
  task("group-disciples", "Manage group disciples and bulletins", "leaderportal", leaders, "Select a group, add disciples, and send a reviewed group bulletin.", [
    s("Choose the group", "my-group-switcher", "Select the group you lead. Confirm the name before adding disciples or sending a message.", { missing: "A coordinator must assign you as a leader of a group before management controls appear." }),
    s("Open the group overview", "my-group-overview", "Open the overview to review the group's leader, disciples, curriculum, and meeting schedule."),
    s("Choose Add Disciple", "my-group-add", "Use Add Disciple to select existing church members for this group.", { reveal: "my-group-overview" }),
    s("Select disciples and save", "my-group-add-form", "Search and filter the available members, check the intended disciples, then submit the addition. Confirm the updated group member list.", { reveal: ["my-group-overview", "my-group-add"], missing: "Select a group you lead and open Add Disciple first." }),
    s("Open a group bulletin", "my-group-bulletin", "Close the disciple form and use the bulletin control for a message to this group's audience.", { reveal: "my-group-overview" }),
    s("Review and broadcast", "my-group-bulletin-form", "Enter a clear subject and complete message. Check the selected group and recipients before choosing Broadcast Bulletin.", { reveal: ["my-group-overview", "my-group-bulletin"], missing: "Select a group you lead and open the bulletin form first." }),
  ]),
];

export const allTaskGuides = [...taskGuides, ...workflowGuides];
const original = (id: string) => taskGuides.find(guide => guide.id === id)!.steps;
const workflow = (id: string) => workflowGuides.find(guide => guide.id === id)!.steps;
const portalSteps = [
  s("Select your Bible study group", "my-group-switcher", "Choose your assigned group. If none appears, ask a coordinator to check your group assignment."),
  s("Review group overview and disciples", "my-group-overview", "Review the leader, disciples, study progress, and meeting schedule. Leaders can add disciples and send a bulletin here."),
  s("Open Curriculum & Roll-Call", "my-group-meetings", "Review the curriculum and meeting sessions. Leaders can record a dated session by selecting present disciples and saving session attendance."),
  s("Review attendance monitoring", "my-group-attendance", "Inspect the available attendance summaries and history for the selected group."),
  s("Review the group's duty", "my-group-duty", "Check the group's duty assignments and upcoming service dates."),
];
// Explicit tours for every routed page; no generic whole-workspace fallback.
const tours: Record<Exclude<NavTab, "leader-dashboard">, GuideStep[]> = {
  plannedvisits: [{ title: 'Prepare to welcome visitors', text: 'Filter planned visits, open their details, and update follow-up notes and status. Mark Visited only after confirming arrival.', target: 'workspace' }],
  dashboard: [
    s("Review church totals", "dashboard-summary", "Check members, members without groups, small groups, and households. Choose a summary to open the related directory.", { roles: managers }),
    s("Read today's passage", "dashboard-reading", "Review today's assigned reading and use Read to open the chapter reader.", { roles: managers }),
    s("Review upcoming gatherings", "dashboard-calendar", "Check the next church activity and open the calendar for dates and details.", { roles: managers }),
    s("Inspect ministry distribution", "dashboard-ministries", "Switch Directory or Chart to compare the age-based ministries. Open Members to inspect assignments.", { roles: managers }),
    s("Review Saturday duty", "dashboard-duty", "Check the assigned Saturday team and upcoming cleaning rotation.", { roles: managers }),
    s("Review Sunday washing", "dashboard-washing", "Check this Sunday's roster lead and assignment, then open the washing roster for later dates.", { roles: managers }),
    s("Review baptism candidates", "dashboard-baptism", "Open the candidate review to inspect qualified people and existing nominations before nominating anyone.", { roles: managers }),
    s("Review your leader summary", "leader-dashboard-summary", "Check your groups, disciples, curriculum, and service assignments.", { roles: ["Leader"] }),
    s("Open your group", "leader-dashboard-group", "Use the group shortcut for disciples, sessions, curriculum, and attendance.", { roles: ["Leader"] }),
    s("Check church activities", "leader-dashboard-calendar", "Open Calendar to inspect the dates and details of upcoming activities.", { roles: ["Leader"] }),
    s("Review volunteer assignments", "volunteer-summary", "Check your Saturday cleaning and Sunday washing assignments, plus attendance duties.", { roles: ["Volunteer"] }),
    s("Open attendance tools", "volunteer-attendance", "Use Attendance Live for individual check-in, guests, special events, and Batch Roll Call.", { roles: ["Volunteer"] }),
    s("Review volunteer schedules", "volunteer-duty", "Open the duty roster to confirm your team, responsibilities, and service date.", { roles: ["Volunteer"] }),
  ],
  members: [
    s("Search and filter the member directory", "member-search", "Search the full name and choose a ministry. Open a matching member to inspect profile, family, baptism, and attendance details."),
    s("Review birthdays", "member-birthday-filter", "Use the birthday shortcuts or birth-month filter to find celebrants."),
    s("Register a member", "member-add", "Use Add Member for the application: identity, birthday, ministry, status, household, contact, parents or guardian, and family details."),
    s("Import applications", "member-import", "Upload a form or file, or paste text. Analyze, review the detected records and duplicate issues, then save selected valid records."),
    s("Review households", "households-tab", "Open Households to inspect shared addresses, parents, and family members. Edit an existing household from its card."),
    s("Create a family household", "household-create", "Use New Household to add the address, parents, children, relatives, and emergency contact. Linked applications reflect these family details."),
  ],
  attendance: [
    original("attendance")[0], original("attendance")[1],
    s("Choose ministry and status filters", "attendance-scope", "Choose All Church or a ministry and check the status filters before searching for a person."),
    original("attendance")[2], original("attendance")[3],
    s("Use Batch Roll Call", "attendance-batch", "Record many people at once. Choose the absentees, present attendees, or selected-present-only method, review the targets, then save.", { details: ["Use Guide me: Use Sunday Batch Roll Call for all three methods and selection controls."] }),
    s("Register a guest", "attendance-guest", "Enter a new guest's name, ministry, phone, and notes on the selected service; submit the guest check-in yourself."),
    s("Record special events", "attendance-event", "Choose an event, review registrations, add walk-ins, and mark individual or batch attendance separately from Sunday worship."),
  ],
  attendancelog: workflow("attendance-history"),
  servicecalendar: [
    s("Switch list and month views", "service-list", "Review the service dates in List or Month view; use month navigation for a date overview."),
    s("Filter service type and status", "service-filters", "Choose Sunday worship or special services and filter Held or Cancelled to narrow the list."),
    s("Generate upcoming Sundays", "service-generate", "Generate Upcoming Sundays creates the missing upcoming worship service dates when you choose it. Check the calendar first, then verify the generated dates afterward."),
    s("Create or edit a service", "service-new", "Create a service with its date, type, title, status, and notes. Use Edit on an existing service to correct it."),
    s("Change service availability", "service-status", "Use a service's status action to switch Held or Cancelled when appropriate. Verify the resulting service status before taking attendance.", { missing: "Create a service first or adjust the filters to show an existing service." }),
  ],
  biblestudy: [
    s("Review active and past groups", "groups-status", "Switch Active, Completed, Archived, or All. Use ministry and meeting-day filters to narrow the directory."),
    s("Search groups", "groups-search", "Find the group by name, topic, leader, location, or reason. Open Details to inspect its disciples and curriculum."),
    s("Set up a group", "group-create", "Set its name, ministry, category, curriculum, leader, schedule, location, capacity, and disciples before saving."),
    s("Inspect group details", "group-details", "Open the intended group to edit its information, review disciples, or record study progress."),
    s("Review group history", "group-history", "Inspect past chapters, notes, and lifecycle changes before completing, archiving, or restoring a group."),
    s("Review transitions", "group-transition", "Review ministry or age transitions and affected people before applying a reassignment."),
  ],
  leaderportal: portalSteps,
  "leader-members": portalSteps,
  "leader-biblestudy": portalSteps,
  curriculum: [
    s("Search books and notes", "curriculum-search", "Find a title or study notes and select the intended topic. Check its total lessons and summary."),
    s("Inspect topic and group use", "curriculum-inspector", "Open the inspector for the selected topic to review chapters, notes, and groups using this material."),
    s("Add or edit study material", "curriculum-new", "Authorized leaders and managers can set the title, lesson count, and study notes, then save the topic.", { roles: leaders }),
  ],
  biblereading: original("reading"),
  duty: [
    s("Review Saturday duty teams", "duty-teams-tab", "Inspect team leaders, members, responsibilities, and rotation order."),
    s("Review Saturday assignments", "duty-schedule-tab", "Find your upcoming Saturday and confirm the team assignment. Managers can arrange a reviewed swap."),
    s("Read cleaning tasks and guidelines", "duty-checklist-tab", "Review the common task checklist, equipment, preparation, and service instructions."),
    s("Set up a duty team", "duty-new", "Managers can create or edit a team, select its members, assign a leader, and set its rotation order.", { roles: managers }),
  ],
  dishwashing: [
    s("Review washing teams", "washing-teams-tab", "Inspect the Bible study, ministry, combined, or custom roster units and their leads."),
    s("Review Sunday rotation", "dishwashing-schedule-tab", "Check this Sunday, next Sunday, and later assignments. Managers can swap two dates or override a single assignment."),
    s("Read kitchen protocols and checklist", "washing-protocols-tab", "Review the sanitation and washing procedures, ordered protocol steps, and checklist tasks."),
    s("Set up a roster team", "washing-new", "Managers can choose roster sources, assign a leader, set order, and save responsibilities.", { roles: managers }),
  ],
  events: workflow("calendar-explore"),
  sundaycycle: [
    s("Choose the celebration year", "celebration-year", "Choose the year you need; recurring celebrations are resolved for that year's dates."),
    s("Filter recurring and one-time events", "celebration-type-filter", "Choose recurring, one-time, or all events and use the quarter filter for a narrower list."),
    s("Search celebrations", "celebration-search", "Find an event by name, theme, or location and review its resolved date and instructions."),
    s("Create or edit a celebration", "celebration-new", "Choose recurring or one-time, set its schedule, theme, venue, and instructions, then save.", { roles: managers }),
    s("Schedule on the calendar", "celebration-sync", "Managers can review the proposed calendar date and attendance settings before scheduling this celebration.", { roles: managers }),
  ],
  communications: [
    ...original("announcements"),
    s("Publish an announcement", "announcement-new", "Managers can enter the title, audience, and complete message, then review and publish the announcement.", { roles: managers }),
  ],
  reports: workflow("analytics"),
  users: [
    s("Search accounts", "users-search", "Find the account holder by name, email, or ministry."),
    s("Filter by role", "users-role-filter", "Choose a role to inspect accounts with comparable access."),
    s("Compare permissions", "users-matrix", "Open the matrix to see the sections and actions available to each role."),
    s("Create an account", "users-new", "Set identity, sign-in details, role, and ministry assignments before saving."),
    s("Inspect or update an account", "users-details", "Open the intended account to review its access, edit permitted details, or start a reviewed password reset."),
  ],
  audit: workflow("audit-review"),
  settings: [
    s("Manage ministry age ranges", "settings-ministries", "Review names, colors, and age bounds used by member ministry assignments."),
    s("Manage Bible study categories", "settings-bible_study_categories", "Maintain the category names, order, descriptions, and active status used for study groups."),
    s("Manage venues", "settings-locations", "Maintain locations used by church meetings and events."),
    s("Manage event categories", "settings-events", "Maintain event types and their available reference information."),
    s("Manage announcement categories", "settings-communications", "Maintain reference categories for church communications."),
    s("Manage membership statuses", "settings-membership", "Review the status labels available on member records."),
    s("Configure notifications and email", "settings-notifications_email", "Review SMTP, sender, recipients, and email rules; save before testing delivery."),
    s("Update church information", "settings-general", "Review church identity, address, contacts, and worship information before saving."),
    s("Review backup and restore", "settings-backup_restore", "Review backup scope, restore file contents, yearly deletion, and cloud sync before executing maintenance actions.", { roles: rootAdmins }),
  ],
  notifications: workflow("notifications"),
  profile: workflow("profile"),
};

// Both dashboard routes render the same role-dependent component.
export const pageTours: Record<NavTab, GuideStep[]> = { ...tours, "leader-dashboard": tours.dashboard };
