import { PoolClient } from "pg";
import {
  addRelationship,
  invalidFamily,
  lockFamily,
  resolvePerson,
  linkFamilyPerson,
  removeRelationship,
} from "./familyTree";
const normalize = (v: unknown) =>
  String(v || "")
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase();
// Parent slots and child roles are explicit connections. Household assignment remains separate.
export async function syncRecordedHouseholdChildren(
  client: PoolClient,
  householdId?: number,
) {
  await lockFamily(client);
  const households = (
    await client.query(
      "SELECT id,father_name,mother_name,guardian_name,family_members FROM households WHERE ($1::integer IS NULL OR id=$1) ORDER BY id",
      [householdId ?? null],
    )
  ).rows;
  if (!households.length) return;
  const members = (
    await client.query(
      "SELECT id,household_id,first_name,last_name FROM members",
    )
  ).rows;
  for (const household of households) {
    const family = Array.isArray(household.family_members)
      ? household.family_members
      : [];
    const personFor = async (
      name: string,
      memberId?: number | null,
    ): Promise<number | undefined> => {
      if (!normalize(name)) return;
      const key = `name:${normalize(name)}`;
      const origin = (
        await client.query(
          "SELECT id,merged_into_id FROM family_people WHERE household_id=$1 AND household_entry_key=$2",
          [household.id, key],
        )
      ).rows[0];
      if (memberId != null) {
        if (!members.some((m) => m.id === memberId)) return;
        if (origin && !origin.merged_into_id)
          return linkFamilyPerson(client, origin.id, memberId);
        return resolvePerson(client, { member_id: memberId });
      }
      // Named identities are scoped to a specific household entry, never merged globally by name.
      if (origin) return origin.merged_into_id || origin.id;
      const matches = members.filter(
        (m) =>
          m.household_id === household.id &&
          normalize(`${m.first_name} ${m.last_name}`) === normalize(name),
      );
      if (matches.length > 1) return;
      if (matches.length === 1)
        return resolvePerson(client, { member_id: matches[0].id });
      const id = await resolvePerson(client, {
        name,
        household_id: household.id,
      });
      await client.query(
        "UPDATE family_people SET household_entry_key=$1 WHERE id=$2",
        [key, id],
      );
      return id;
    };
    type Role = "father" | "mother" | "guardian" | "spouse";
    const parents: { id: number; role: Role }[] = [];
    for (const role of ["father", "mother", "guardian"] as const) {
      const name = household[`${role}_name`];
      if (!normalize(name)) continue;
      const entries = family.filter(
        (p: any) =>
          [role, role === 'father' ? 'husband' : role === 'mother' ? 'wife' : role].includes(normalize(p.relationship)) &&
          normalize(p.name) === normalize(name),
      );
      if (entries.length > 1) continue;
      const id = await personFor(name, entries[0]?.member_id);
      if (id) parents.push({ id, role });
    }
    const desired: { from: number; to: number; role: Role }[] = [];
    const couple = parents.filter(p => p.role !== 'guardian' && family.some((entry: any) =>
      normalize(entry.relationship) === (p.role === 'father' ? 'husband' : 'wife') && normalize(entry.name) === normalize(household[`${p.role}_name`])));
    if (couple.length === 2) desired.push({from:Math.min(couple[0].id,couple[1].id),to:Math.max(couple[0].id,couple[1].id),role:'spouse'});
    for (const entry of family) {
      if (
        ["father", "mother", "guardian", "husband", "wife"].includes(normalize(entry.relationship))
      )
        continue;
      const id = await personFor(entry.name, entry.member_id);
      if (!id) continue;
      if (["son", "daughter", "child"].includes(normalize(entry.relationship)))
        for (const parent of parents)
          desired.push({ from: parent.id, to: id, role: parent.role });
      const heads = parents.filter(parent => parent.role !== "guardian");
      if (normalize(entry.relationship) === "spouse" && heads.length === 1)
        desired.push({from: Math.min(heads[0].id,id),to: Math.max(heads[0].id,id),role:"spouse"});
    }
    const kindOf = (role: Role) =>
      role === "guardian" ? "guardian" : role === "spouse" ? "spouse" : "parent";
    const owned = (
      await client.query(
        "SELECT * FROM family_relationships WHERE source_household_id=$1 AND deleted_at IS NULL",
        [household.id],
      )
    ).rows;
    for (const edge of owned) {
      // Only links generated by this household follow its saved roster.
      // Explicit relationships from the tree manager are not removed here.
      if (
        !desired.some(
          (d) =>
            d.from === edge.from_person_id &&
            d.to === edge.to_person_id &&
            kindOf(d.role) === edge.kind &&
            (d.role === "guardian" || d.role === "spouse" || d.role === edge.parent_role),
        )
      ) {
        if (edge.kind === "spouse") await removeRelationship(client,edge.id);
        await client.query(
          "UPDATE family_relationships SET deleted_at=CURRENT_TIMESTAMP,source_removed=TRUE WHERE id=$1",
          [edge.id],
        );
      }
    }
    for (const d of desired) {
      const kind = kindOf(d.role);
      const history = (
        await client.query(
          "SELECT * FROM family_relationships WHERE kind=$1 AND to_person_id=$2",
          [kind, d.to],
        )
      ).rows;
      if (history.some((edge) => edge.deleted_at && !edge.source_removed))
        continue;
      const recorded = history.find(edge => !edge.deleted_at && edge.from_person_id === d.from && (kind === "guardian" || kind === "spouse" || edge.parent_role === d.role));
      // Do not take ownership of an explicit link or another household's link.
      if (recorded && recorded.source_household_id !== household.id) continue;
      if (
        history.some(
          (edge) =>
            !edge.deleted_at &&
            edge.from_person_id !== d.from &&
            (kind === "guardian" || kind === "spouse" || edge.parent_role === d.role),
        )
      ) {
        if (householdId !== undefined)
          invalidFamily(
            "This child has a different confirmed parent. Correct it in Manage Relationships before saving this household.",
          );
        continue;
      }
      await client.query("SAVEPOINT household_child_link");
      try {
        const id = await addRelationship(
          client,
          d.from,
          d.to,
          kind,
          d.role === "guardian" || d.role === "spouse" ? undefined : d.role,
          true,
        );
        await client.query(
          "UPDATE family_relationships SET source_household_id=$1,source_removed=FALSE WHERE id=$2",
          [household.id, id],
        );
        await client.query("RELEASE SAVEPOINT household_child_link");
      } catch (error: any) {
        await client.query("ROLLBACK TO SAVEPOINT household_child_link");
        await client.query("RELEASE SAVEPOINT household_child_link");
        if (error.status !== 400 || householdId !== undefined) throw error;
      }
    }
  }
}
